"""initial migration

Revision ID: 713abce006be
Revises: 
Create Date: 2023-12-05 15:02:48.303167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713abce006be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gan_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gan_parameters', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
